name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: 'package.json'
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: Install deps
        run: |
          pnpm install 
      - name: Run Jest tests
        uses: willcaul/jest-github-action@v1.0.2  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "pnpm test"
