name: Unit Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  Jest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: 'package.json'
    - name: Node Setup
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
    - name: Run Jest tests
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        package-manager: pnpm
        test-script: "pnpm test --"
  Readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: 'package.json'
    - name: Node Setup
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
    - name: Build Docs
      run: |
        pnpm run docs
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Regenerate README